import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import { Theme } from "@radix-ui/themes";
import AuthProvider from "./auth/Provider";
import ReactQueryProvider from "./ReactQueryProvider";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <AuthProvider>
            <Theme accentColor="violet" radius="small">
              <Navbar />
              <main>{children}</main>
            </Theme>
          </AuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
